---

- name: setup redis configuration
  become: true
  template: src="{{ item.src }}" dest="{{ item.dest }}"
  with_items: "{{ _redis.templates | default([]) }}"
  when:
    - _redis.templates is defined
  notify:
    - restart redis-server
  tags:
    - redis
